# Generated by Django 5.2.7 on 2025-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescateComida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
